### ISSUE TITLE
Wrong email address obtained from Azure oAuth

### ISSUE THREAD

**Issue by ryannix123** [marknadig/omniauth-azure-oauth2#17]
The oAuth plug-in is working great, except one thing: The user’s email address is incorrect. The plug-in is populating the email address as the short name and the Active Directory domain, neither of which are correct. Example my email address is r-nix@mycollege.edu but the oAuth plugin is making the email address rtn456@ad.mycollege.edu. Is there a way to add something to the code that populates the user account as the ‘mail’ attribute in LDAP or Active Directory. https://meta.discourse.org/t/discourse-azure-ad-plugin-not-working/65249/10

**Comment by marknadig** [comment]
Hi @ryannix123 , thanks for the report. I'm not in a position to test this out at the moment, however it appears that we're just grabbing the 'email' attribute returned from Azure. 
line 52 of  ./lib/omniauth/strategies/azure_oauth2.rb

**Comment by ryannix123** [comment]
Thanks, @marknadig . I'm looking at our Azure AD right now and seems the email field isn't populated at all. I'll contact our campus support to see if we can sync the email attribute. Maybe that will fix things.

**Comment by ryannix123** [comment]
Hi @marknadig, when you say the "email" attribute, are you saying the "mail" attribute is the one being used? I checked with our IT team and the "mail" attribute is indeed being synced. The guy I spoke with says the that Azure AD tends to favor the UPN instead of the actual "mail" address.

**Comment by tim-vandecasteele** [comment]
Hi @ryannix123 we're having the same problem at our end. Did you manage to get this fixed in the end?

**Comment by marknadig** [comment]
hi @ryannix123 , I'm not sure what fix needs to happen. Ryan reported that we're grabbing "mail", but https://github.com/KonaTeam/omniauth-azure-oauth2/blob/master/lib/omniauth/strategies/azure_oauth2.rb#L52 shows we're grabbing "mail" or "upn"

**Comment by ryannix123** [comment]
Hi All,

Unfortunately the issue persists. I wonder if we can call a different AD attribute instead? I spot checked my own AD account and the email address is correct. However, this plug-in still seems to favor the UPN instead. 
I spoke with our campus Exchange admins and it doesn't sound like we can universally change the UPN to make it match up with the SMTP address in the record. There are dozens of Powershell scripts to change the UPN but It's not a technical issue as much as it's an "unknown" issue. i.e. what will break? It would be best to adjust this in the plugin if possible. 

https://blogs.perficient.com/microsoft/2015/07/office-365-why-your-upn-should-match-your-primary-smtp-address/

- Ryan

**Comment by marknadig** [comment]
hi @ryannix123 , re: "this plug-in still seems to favor the UPN instead."  here's the code
`email: raw_info['email'] || raw_info['upn']`

That looks like it is favoring the email attribute to me.  If you trace through in your local case, wondering if the smtp address is coming through a completely different attribute in raw_info.

**Comment by ryannix123** [comment]
Thanks, @marknadig I'll work with my people to see if we can trace it back.

**Comment by tim-vandecasteele** [comment]
Hi @marknadig seems you closed this issue, was the origin of this one found? 

I tried to debug this the last few days, but couldn't really find the actual email address in my responses (the 'email' attribute was never returned, I only got the 'upn' anyway).

**Comment by marknadig** [comment]
Hi @tim-vandecasteele . I was being OCD... there's no consensus on what's really going on, just speculation. I'm not able to dive in right now. The code is looking for 'email' first and then 'upn'. I'm not sure why neither of these would be populated for some folks. Happy to re-open and see if anyone can give specifics.

**Comment by tim-vandecasteele** [comment]
Hi @marknadig, I found the following on a Microsoft forum:

> In the email claim we use Primary SMTP email address. This is reserved field from Exchange. When you assign the Office 365 license to the user then it will create a Primary email box for a user and at that time this field will get populated for a user. You cant write this field manually. After that only you will see the email claim value in the token.

So I think in some (most?) cases it's just not possible to fetch the actual email address

**Comment by tmaier** [comment]
Hi, 
did you find a solution?

Did you check the Microsoft documentation? 
https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens

> The `email` claim is present by default for guest accounts that have an email address.  Your app can request the email claim for managed users (those from the same tenant as the resource) using the `email` [optional claim](active-directory-optional-claims.md
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims).  On the v2.0 endpoint, your app can also request the `email` OpenID Connect scope - you don't need to request both the optional claim and the scope to get the claim.  The email claim only supports addressable mail from the user's profile information.

**Comment by tmaier** [comment]
I see two options:

# given we use v1.0 Azure AD API endpoint:
* There is an optional claim `email`: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims
* This article describes how to set an optional claim in the Azure Portal: <https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#optional-claims-example>
* Basically, one must download the `Azure Active Directory app manifest`, modify it and upload it again. <https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest>

My verdict: This sounds complicated and error prone.

# consider change to v2.0 Azure AD API endpoint
* This has its own set of limiations. See <https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison>
* Set the `scope` `email` on authorization
* This can be achieved via overriding the `authorize_params` method and returning a hash with a `scope` key. See example <https://github.com/omniauth/omniauth-oauth2/blob/01fbfb5f8613a8f6bf1bf661a0f29ea9f8e2c26b/spec/omniauth/strategies/oauth2_spec.rb#L52>

My verdict: This requires an upgrade to API version v2.0

**Comment by marknadig** [comment]
I agree. There's a PR for #28 . Closing this
